config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all

  root 'boards#index'

  resources :boards, param: :short_name do
    resources :comment_threads, only: %i[show create destroy], path: 'threads' do
      shallow { resources :comments, only: %i[destroy create] }
      member do
        put :lock
        put :unlock
      end
    end
  end

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    get    'sign_in',  to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  authenticate :user, ->(user) { user.min_role?(:owner) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/comment_thread.rb
class CommentThread < ApplicationRecord
  has_many :comments, -> { least_recent_first }, dependent: :delete_all, after_add: :bump_thread
  accepts_nested_attributes_for :comments
  validates_with CommentThreadValidator

  belongs_to :board

  before_commit do
    self.hidden = false if hidden.nil?
    self.sticky = false if sticky.nil?
    self.locked = false if locked.nil?
  end

  def lock
    self.locked = true
    save
  end

  def unlock
    self.locked = false
    save
  end

  def hide
    self.hidden = true
    save
  end

  def unhide
    self.hidden = false
    save
  end

  BUMP_LIMIT = 100
  GALLERY_LIMIT = 50

  scope :most_recent_first, -> { order('created_at DESC') }
  scope :least_recent_first, -> { order('created_at ASC') }
  scope :feed, -> { where.not(hidden: true).order('sticky DESC NULLS LAST, last_bump DESC NULLS LAST, created_at DESC').limit(GALLERY_LIMIT) }

  private

  def bump_thread(record)
    self.touch if self.persisted?
    self.bump_count ||= 0
    self.bump_count += 1
    self.last_bump = Time.current if bump_count < BUMP_LIMIT
  end
end

app/controllers/comment_threads_controller.rb
class CommentThreadsController < BoardsBaseController
  before_action :redirect_unless_board
  before_action :redirect_unless_thread, only: %i[show destroy lock unlock]

  def show
    authorize! :read, current_thread

    @comments = current_thread.comments.least_recent_first.all.decorate
    @comment = current_thread.comments.build
    @board = current_board.decorate
    respond_to do |format|
      format.html
    end
  end

  def create
    authorize! :create, @board.threads.build
    
    result = Comments::PostThread.call(user: current_user, board: current_board,
                                       anon_name: current_anon_name, params: create_params)
    if result.success?
      redirect_to board_comment_thread_url(current_board, result.thread), notice: 'Thread created succesfully'
    else
      @thread = result.thread
      @comment = result.comment.decorate
      @threads = current_board.threads.feed.decorate
      @board = current_board.decorate
      flash.now[:alert] = result.message
      render 'boards/show', status: :unprocessable_entity
    end
  end

  def unlock
    authorize! :unlock, current_thread

    current_thread.unlock
    redirect_back_or_to board_url(current_board), notice: "Unlocked thread #{current_thread.id}"
  end

  def lock
    authorize! :lock, current_thread

    current_thread.lock
    redirect_back_or_to board_url(current_board), notice: "Locked thread #{current_thread.id}"
  end
  
  def destroy
    authorize! :destroy, current_thread

    if current_thread.destroy
      redirect_to board_url(current_board), notice: "Thread #{params[:id]} destroyed", status: :see_other
    else
      flash.now[:alert] = "Problem deleting #{params[:id]}"
      render 'show', status: :unprocessable_entity
    end
  end

  private

  def create_params
    @thread = @board.threads.build
    permitted_attrs = []
    permitted_attrs << :locked if can?(:lock, @thread)
    permitted_attrs << :sticky if can?(:sticky, @thread)
    params.permit(comment_thread: permitted_attrs, comment: %i[content image])
  end

  def current_ability
    @current_ability ||= ThreadAbility.new(current_user)
  end

  def current_thread
    @thread = current_board&.threads&.find(params[:id])
  end
end

app/helpers/comment_threads_helper.rb
module CommentThreadsHelper
  def new_comment_form(board:, thread:, comment:)
    render partial: 'comment_threads/new_comment_form', locals: { board: board, thread: thread, comment: comment }
  end

  def lock_or_unlock(thread:, authorized: false)
    if thread.locked?
      path = unlock_board_comment_thread_path(thread.board, thread)
      icon_or_link('lock', 'Unlock', path, authorized)
    else
      path = lock_board_comment_thread_path(thread.board, thread)
      icon_or_link('unlock', 'Lock', path, authorized)
    end
  end

  private

  def icon_or_link(icon, text, path, authorized)
    if authorized
      ficon = fa_icon(icon, text: text)
      link_to(ficon, path, data: { "turbo-method": :put })
    else
      fa_icon(icon)
    end
  end
end

app/views/comment_threads/_new_comment_form.html.haml
= render 'shared/error_messages', object: thread
= render 'shared/error_messages', object: comment
.flex.justify-center
  = form_with model: comment, url: [board, thread, comment], local: true, multipart: true do |f|
    .field
      = f.label :content, 'New Comment'
      %br/
      = f.text_area :content, cols: 60, rows: 5, class: ['form-field']
    .field.inline-block
      = f.hidden_field(:image, value: comment.cached_image_data) if comment.cached_image_data
      = f.file_field :image
    .actions.inline-block
      = f.submit 'Submit'

app/views/comment_threads/_new_thread_form.html.haml
= render 'shared/error_messages', object: thread
= render 'shared/error_messages', object: comment
.flex.justify-center
  = form_with model: thread, url: [board, thread], local: true, multipart: true do |f|
    = fields_for :comment, comment do |c_fields|
      .field
        = c_fields.label :content, 'New Thread'
        %br/
        = c_fields.text_area :content, cols: 60, rows: 5, class: ['form-field']
      .field.inline-block
        = c_fields.hidden_field(:image, value: comment.cached_image_data) if comment.cached_image_data
        = c_fields.file_field :image
    .actions.inline-block
      - if can?(:sticky, thread)
        = f.label :sticky
        = f.check_box :sticky
      = f.submit 'Submit'

app/views/comment_threads/show.html.haml
- provide(:title, "Thread ##{@thread.id}")
%h1.text-center
  = link_to @board.slash_name, board_path(@board), class: ['form-link']
  Thread ##{@thread.id}
%h2.text-center
  Replies: #{@comments.count}
  -if @thread.sticky?
    = fa_icon('bookmark')
  = lock_or_unlock(thread: @thread, authorized: can?(:lock, @thread))
- if @thread.locked?
  %h2.text-center.text-emerald-300
    Thread Locked
- if can?(:create, @comment)
  = new_comment_form(board: @board, thread: @thread, comment: @comment)
.divide-y.px-20
  = turbo_stream_from [@thread, :comments]
  = turbo_frame_tag [@thread, :comments] do
    = render partial: 'comments/comment', collection: @comments, cached: true