config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all

  root 'boards#index'

  resources :boards, param: :short_name do
    resources :comment_threads, only: %i[show create destroy], path: 'threads' do
      shallow { resources :comments, only: %i[destroy create] }
      member do
        put :lock
        put :unlock
      end
    end
  end

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    get    'sign_in',  to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  authenticate :user, ->(user) { user.min_role?(:owner) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_debug.html.haml
- if Rails.env.development?
  .w-fit.block.mx-auto.text-center
    %h2.font-mono.text-xl Debug
    .bg-indigo-100.h-max.px-4.py-4
      = debug(params)
      = debug_console(yield(:debug_object))

app/views/layouts/_header.html.haml
%header.block.px-8.py-4.flex.flex-row
  %h1{class: ['basis-1/4']}
    = link_to "Rails Imageboard", root_path
  %nav{class: ['basis-3/4', 'flex', 'justify-end']}
    %ul
      - if min_role?(:daemon)
        %li.px-2.inline-block
          = link_to 'Manage Site'
      - if min_board_role?(:moderator)
        %li.px-2.inline-block
          = link_to 'Manage Board'
      %li.px-2.inline-block
        - if user_signed_in?
          = link_to 'Sign out', sign_out_path, data: { "turbo-method": :delete }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "tailwind", "inter-font"
    = javascript_importmap_tags
  %body
    = render 'layouts/header'
    %div.container.w-screen.mx-auto
      - unless flash.empty?
        .form_panel
          - flash.each do |message_type, message|
            = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/debug'